application:
  layer: "development"

logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
  slow_query_threshold_in_ms: 2000

bearfacts_proxy:
  fake: true

blog_latest_release_notes_feed_proxy:
  fake: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>

cal_link_proxy:
  fake: true

canvas_proxy:
  fake: true

cas_server: 'https://auth-test.berkeley.edu/cas'

cas_logout_url: 'https://auth-test.berkeley.edu/cas/logout'

financials_proxy:
  fake: true

textbooks_proxy:
  fake: true

google_proxy:
  fake: true

myfinaid_proxy:
  fake: true

cal1card_proxy:
  fake: true

postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_development' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_development' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>

campusdb:
  fake: true

edodb:
  fake: true

ist_jms:
  fake: true
  enabled: false

hot_plate:
  enabled: false

advising_proxy:
  fake: true

features:
  advising: true
  audio: true
  cal1card: true
  class_enrollment_summer_2016: true
  course_manage_official_sections: true
  cs_academic_planner: true
  cs_academic_progress_report: true
  cs_advising_gte_forms: true
  cs_advising_show_advisors: true
  cs_advisor_student_lookup: true
  cs_billing: true
  cs_delegated_access: true
  cs_enrollment_card: true
  cs_fin_aid: true
  cs_holds: true
  cs_logout: true
  cs_profile_emergency_contacts: true
  cs_profile_languages: true
  cs_profile_work_experience: true
  my_fin_aid: true
  prevent_acting_as_users_from_posting: false
  reauthentication: false
  textbooks: true
  videos: true
